### ISSUE TITLE
Some observation stable URLs do not work

### ISSUE THREAD

**Issue by kcs3** [CBIIT/nci-ctd2-dashboard#377]
Search for gene AKT1.  For the first two hits, from Columbia, clicking on the "details" link does not bring up the observation; instead, nothing happens.
However, for the third observation, from Dana Farber, the "details" link works correctly.

**Comment by zhouji2013** [comment]
The issue was caused by the submission names that are longer than the pre-set limit AND are only different in the few ending letters. Fixed by increasing the limit.

**Comment by kcs3** [comment]
Tested the fix in production release v2.53.1_20180514.  The problem still exists as before.  An example URL is

https://ctd2-dashboard.nci.nih.gov/dashboard/#observation/20160825-columbia-piovan-akt-nr3c1-inh-0

This same URL is shown by both of the two Columbia observations mentioned in the search example above when hovering the cursor over the "details" button.

**Comment by zhouji2013** [comment]
The last issue reported turned out to be some deployment problem and has been fixed.

**Comment by kcs3** [comment]
Following redeployment on the NCI side, this issue has now been successfully tested in production and is confirmed resolved.  Both Zhou and I tested.  Closing issue.
